#!/usr/bin/env node
const program = require("commander");

program
    .version("0.1.0")
    .usage("<command> [options...]")
    .command("in", "Punch in at the current time.")
    .command("out", "Punch out at the current time.")
    .parse(process.argv);

