#!/usr/bin/env node
const program = require("commander");


program
  .version("0.1.0")
  .usage("<command> [options...]")
  .arguments("<command> [options]")
  // #region Commands
  .command("punch")    
  .action(() => program.help())
  .command("in", "Punch in at the current time.")
  .command("list [start] [end]", "List punches between a given start and end date.")
  .command("out", "Punch out at the current time.")
  .command("server", "Opens a web page to view and edit punches.")
  // #endregion
  .parse(process.argv);

